/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumePreviewRouteImport } from './routes/resume-preview'
import { Route as IndexRouteImport } from './routes/index'

const ResumePreviewRoute = ResumePreviewRouteImport.update({
  id: '/resume-preview',
  path: '/resume-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume-preview': typeof ResumePreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume-preview': typeof ResumePreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume-preview': typeof ResumePreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resume-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resume-preview'
  id: '__root__' | '/' | '/resume-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumePreviewRoute: typeof ResumePreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-preview': {
      id: '/resume-preview'
      path: '/resume-preview'
      fullPath: '/resume-preview'
      preLoaderRoute: typeof ResumePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumePreviewRoute: ResumePreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
